import React from 'react';

import { Alert, Content, Stack, StackItem } from '@patternfly/react-core';

import links from '~/common/installLinks.mjs';
import { CheckboxField, TextInputField } from '~/components/clusters/wizards/form';
import {
  cloudWatchLogGroupTooltip,
  cloudWatchRoleArnTooltip,
  groupsApplicationsAvailableTooltip,
  groupsApplicationsChosenTooltip,
} from '~/components/clusters/wizards/rosa/LogForwarding/logForwardingTooltips';
import ExternalLink from '~/components/common/ExternalLink';

import { ClusterLogForwardingGroupsApplicationsSelector } from './ClusterLogForwardingGroupsApplicationsSelector';

type LogForwardingCloudWatchFormFieldsProps = {
  logGroupNameField?: string;
  roleArnField?: string;
  selectedItemsField?: string;
  prerequisiteAckField?: string;
  showPrerequisites?: boolean;
};

export function LogForwardingCloudWatchFormFields({
  logGroupNameField = 'logGroupName',
  roleArnField = 'roleArn',
  selectedItemsField = 'selectedItems',
  prerequisiteAckField = 'prerequisiteAck',
  showPrerequisites = false,
}: LogForwardingCloudWatchFormFieldsProps) {
  return (
    <Stack hasGutter>
      {showPrerequisites ? (
        <StackItem>
          <Alert variant="info" isInline title="Prerequisite">
            <Stack hasGutter>
              <StackItem>
                <Content component="p">
                  To use a CloudWatch log group, you must create an IAM role and policy.{' '}
                  <ExternalLink href={links.LOG_FORWARDING_DOCS}>Learn more</ExternalLink>
                </Content>
              </StackItem>
              <StackItem>
                <CheckboxField
                  name={prerequisiteAckField}
                  label="I've read and completed all the prerequisites and am ready to continue."
                />
              </StackItem>
            </Stack>
          </Alert>
        </StackItem>
      ) : null}
      <StackItem>
        <TextInputField
          name={logGroupNameField}
          label="Log group name"
          formGroup={{ isRequired: true }}
          tooltip={cloudWatchLogGroupTooltip}
          helperText="Use the autogenerated name, or provide a custom one"
        />
      </StackItem>
      <StackItem>
        <TextInputField
          name={roleArnField}
          label="Role ARN"
          formGroup={{ isRequired: true }}
          tooltip={cloudWatchRoleArnTooltip}
        />
      </StackItem>
      <StackItem>
        <ClusterLogForwardingGroupsApplicationsSelector
          name={selectedItemsField}
          isRequired
          availableTooltip={groupsApplicationsAvailableTooltip}
          chosenTooltip={groupsApplicationsChosenTooltip}
        />
      </StackItem>
    </Stack>
  );
}
