export const queryConstants = {
  STALE_TIME_60_SEC: 60000,
  AlWAYS_GET_NEW_DATA_STALE_TIME: 0,
  API_PAGE_SIZE: 500,
  FETCH_CLUSTERS_QUERY_KEY: 'fetchClusters',
  FETCH_CLUSTER_DETAILS_QUERY_KEY: 'fetchClusterDetails',
  FETCH_CLUSTER_CONTROL_PLANE_LOG_FORWARDERS: 'fetchClusterControlPlaneLogForwarders',
  FETCH_LOG_FORWARDING_GROUPS_CATALOG: 'fetchLogForwardingGroupsCatalog',
  FETCH_CLUSTER_LOGS_QUERY_KEY: 'fetchClusterLogs',
  FETCH_CLUSTER_STATUS_MONITOR_INFLIGHT_CHECKS: 'fetchClusterStatusMonitorInflightChecks',
  FETCH_CLUSTERS_REFETCH_INTERVAL: 60000, // milliseconds
  FETCH_REGIONALIZED_MULTI_REGIONS: 'fetchRegionalizedMultiRegions',
  FETCH_SEARCH_CLUSTER_NAME: 'fetchSearchClusterName',
  FETCH_SEARCH_DOMAIN_PREFIX: 'fetchSearchDomainPrefix',
  FETCH_GET_OCM_ROLE: 'fetchGetOCMRole',
  FETCH_GET_USER_OIDC_CONFIGURATIONS: 'fetchGetOidcConfigurations',
  FETCH_ACCESS_TRANSPARENCY: 'fetchAccessTransparency',
  FETCH_GET_AVAILABLE_REGIONAL_INSTANCES: 'fetchGetAvailableRegionalInstances',
  FETCH_MULTI_REGION_AVAILABLE_REGIONS: 'fetchGetMultiRegionAvailableRegions',
  FETCH_ORG_AND_QUOTA: 'fetchOrganizationAndQuota',
  FETCH_CAN_CREATE_MANAGED_CLUSTER: 'fetchCanCreateManagedCluster',
};
