import React from 'react';
import { useField } from 'formik';

import { Alert, Content, Stack, StackItem, Title } from '@patternfly/react-core';

import { CheckboxField, TextInputField } from '~/components/clusters/wizards/form';
import { FieldId } from '~/components/clusters/wizards/rosa/constants';
import ExternalLink from '~/components/common/ExternalLink';

import { LogForwardingGroupsApplicationsSelector } from './LogForwardingGroupsApplicationsSelector';
import {
  cloudWatchLogGroupTooltip,
  cloudWatchRoleArnTooltip,
  groupsApplicationsAvailableTooltip,
  groupsApplicationsChosenTooltip,
} from './logForwardingTooltips';

const CLOUDWATCH_PREREQUISITES_HREF =
  'https://docs.openshift.com/rosa/cluster_admin/rosa-configuring-log-forwarding.html';

export function CloudWatchLogForwarding() {
  const [{ value: cwEnabled }] = useField<boolean>(FieldId.LogForwardingCloudWatchEnabled);

  return (
    <Stack hasGutter>
      <StackItem>
        <Title headingLevel="h4">CloudWatch</Title>
      </StackItem>
      <StackItem>
        <CheckboxField
          name={FieldId.LogForwardingCloudWatchEnabled}
          label="Enable CloudWatch"
          helperText="Used for real-time monitoring and analysis"
        />
      </StackItem>
      {cwEnabled ? (
        <StackItem>
          <Stack hasGutter>
            <StackItem>
              <Alert variant="info" isInline title="Prerequisite">
                <Stack hasGutter>
                  <StackItem>
                    <Content component="p">
                      To use a CloudWatch log group, you must create an IAM role and policy.{' '}
                      <ExternalLink href={CLOUDWATCH_PREREQUISITES_HREF}>Learn more</ExternalLink>
                    </Content>
                  </StackItem>
                  <StackItem>
                    <CheckboxField
                      name={FieldId.LogForwardingCloudWatchPrerequisiteAck}
                      label="I've read and completed all the prerequisites and am ready to continue creating my cluster."
                    />
                  </StackItem>
                </Stack>
              </Alert>
            </StackItem>
            <StackItem>
              <TextInputField
                name={FieldId.LogForwardingCloudWatchLogGroupName}
                label="Log group name"
                formGroup={{ isRequired: true }}
                placeHolderText="/aws/control-plane/cluster-name"
                helperText="Use the autogenerated name, or provide a custom one"
                tooltip={cloudWatchLogGroupTooltip}
              />
            </StackItem>
            <StackItem>
              <TextInputField
                name={FieldId.LogForwardingCloudWatchRoleArn}
                label="Role ARN"
                formGroup={{ isRequired: true }}
                tooltip={cloudWatchRoleArnTooltip}
              />
            </StackItem>
            <StackItem>
              <LogForwardingGroupsApplicationsSelector
                name={FieldId.LogForwardingCloudWatchSelectedItems}
                isRequired
                availableTooltip={groupsApplicationsAvailableTooltip}
                chosenTooltip={groupsApplicationsChosenTooltip}
              />
            </StackItem>
          </Stack>
        </StackItem>
      ) : null}
    </Stack>
  );
}
