name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - 'main'

jobs:
  install:
    name: Install
    concurrency:
      group: install-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.node-version }}
      cancel-in-progress: true
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v5
        with:
          path: './node_modules'
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: npm ci
      - name: Check uncommitted changes
        if: ${{ always() }}
        # Check that Git working tree is clean after running `install` command.
        # The `git` command exits with 1 and fails the build if there are any uncommitted changes.
        run: git diff HEAD --exit-code
  build:
    name: Build
    concurrency:
      group: build-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.node-version }}
      cancel-in-progress: true
    needs: install
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache/restore@v4
        with:
          path: './node_modules'
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          fail-on-cache-miss: true
      - name: Build
        run: npm run build
  lint:
    name: Lint
    concurrency:
      group: lint-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.node-version }}
      cancel-in-progress: true
    needs: install
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache/restore@v4
        with:
          path: './node_modules'
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          fail-on-cache-miss: true
      - name: Lint
        run: npm run lint-prettier
  unit-tests:
    name: Unit Tests
    concurrency:
      group: unit-tests-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.node-version }}
      cancel-in-progress: true
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache/restore@v4
        with:
          path: './node_modules'
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          fail-on-cache-miss: true
      - name: Test
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./unitTestCoverage/lcov.info
          flags: unittests
          name: uhc-portal-coverage
          fail_ci_if_error: false
          verbose: true
  circular-dependencies:
    name: Circular Dependencies
    concurrency:
      group: circular-dependencies-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.node-version }}
      cancel-in-progress: true
    needs: [build]
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [24.x]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache/restore@v4
        with:
          path: './node_modules'
          key: ${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          fail-on-cache-miss: true
      - name: Find Circular Dependencies
        run: npm run find-circular-dependencies
