import { Version } from '~/types/clusters_mgmt.v1';

const versionsData: Version[] = [
  {
    kind: 'Version',
    raw_id: '5.0.1',
    id: '5.0.1',
    enabled: true,
    default: false,
    channel_group: 'stable',
    rosa_enabled: true,
    hosted_control_plane_enabled: true,
    gcp_marketplace_enabled: true,
    end_of_life_timestamp: '2026-09-17T00:00:00Z',
  },
  {
    kind: 'Version',
    raw_id: '4.18.3',
    id: '4.18.3',
    enabled: true,
    default: false,
    channel_group: 'stable',
    rosa_enabled: true,
    hosted_control_plane_enabled: true,
    gcp_marketplace_enabled: true,
    end_of_life_timestamp: '2026-09-17T00:00:00Z',
  },
  {
    kind: 'Version',
    raw_id: '4.18.3',
    id: '4.18.3 (eus)',
    enabled: true,
    default: false,
    channel_group: 'eus',
    rosa_enabled: true,
    hosted_control_plane_enabled: true,
    gcp_marketplace_enabled: true,
    end_of_life_timestamp: '2026-09-17T00:00:00Z',
  },
  {
    kind: 'Version',
    raw_id: '4.18.3',
    id: '4.18.3 (fast)',
    enabled: true,
    default: false,
    channel_group: 'fast',
    rosa_enabled: true,
    hosted_control_plane_enabled: true,
    gcp_marketplace_enabled: true,
    end_of_life_timestamp: '2026-09-17T00:00:00Z',
  },
  {
    kind: 'Version',
    raw_id: '4.18.1',
    id: '4.18.1',
    enabled: true,
    default: false,
    channel_group: 'stable',
    rosa_enabled: true,
    hosted_control_plane_enabled: true,
    gcp_marketplace_enabled: true,
    end_of_life_timestamp: '2026-09-17T00:00:00Z',
  },
  {
    kind: 'Version',
    raw_id: '4.18.0',
    id: '4.18.0 (eus)',
    enabled: true,
    default: false,
    channel_group: 'eus',
    rosa_enabled: true,
    hosted_control_plane_enabled: true,
    gcp_marketplace_enabled: true,
    end_of_life_timestamp: '2026-09-17T00:00:00Z',
  },
  {
    kind: 'Version',
    raw_id: '4.17.9',
    id: '4.17.9 (fast)',
    enabled: true,
    default: false,
    channel_group: 'fast',
    rosa_enabled: true,
    hosted_control_plane_enabled: true,
    gcp_marketplace_enabled: true,
    end_of_life_timestamp: '2026-09-17T00:00:00Z',
  },
  {
    kind: 'Version',
    raw_id: '4.13.1',
    id: '4.13.1',
    enabled: true,
    default: false,
    channel_group: 'stable',
    rosa_enabled: true,
    hosted_control_plane_enabled: true,
    gcp_marketplace_enabled: true,
    end_of_life_timestamp: '2024-09-17T00:00:00Z',
  },
  {
    kind: 'Version',
    raw_id: '4.12.13',
    id: '4.12.13',
    enabled: true,
    default: true,
    channel_group: 'stable',
    rosa_enabled: true,
    hosted_control_plane_enabled: true,
    gcp_marketplace_enabled: true,
    end_of_life_timestamp: '2024-09-17T00:00:00Z',
  },
  {
    kind: 'Version',
    raw_id: '4.12.12',
    id: '4.12.12',
    enabled: true,
    default: false,
    channel_group: 'stable',
    rosa_enabled: true,
    hosted_control_plane_enabled: true,
    gcp_marketplace_enabled: true,
    end_of_life_timestamp: '2024-09-17T00:00:00Z',
  },
];

const lifecycleResponseData = {
  data: [
    {
      uuid: '0964595a-151e-4240-8a62-31e6c3730226',
      name: 'Red Hat OpenShift Container Platform',
      former_names: [],
      opl_uuid: null,
      show_final_minor_release: false,
      is_layered_product: false,
      all_phases: [
        {
          name: 'General availability',
          ptype: 'normal',
          tooltip: null,
          display_name: 'General availability',
          additional_text: '',
        },
        {
          name: 'Full support',
          ptype: 'normal',
          tooltip: null,
          display_name: 'Full support ends',
          additional_text: '',
        },
        {
          name: 'Maintenance support',
          ptype: 'normal',
          tooltip: null,
          display_name: 'Maintenance support ends',
          additional_text: '',
        },
        {
          name: 'Extended update support',
          ptype: 'normal',
          tooltip: null,
          display_name: 'Extended update support ends',
          additional_text: '',
        },
        {
          name: 'Extended update support Term 2',
          ptype: 'extended',
          tooltip:
            'The Extended Life Cycle Phase (ELP) is the post-retirement time period. We require that customers running Red Hat Enterprise Linux products beyond their retirement continue to have active subscriptions which ensures that they continue receiving access to all previously released content, documentation, and knowledge base articles as well as receive limited technical support. As there are no bug fixes, security fixes, hardware enablement, or root cause analysis available during the Extended Life Phase, customers may choose to purchase the Extended Life Cycle Support Add-On during the Extended Life Phase, which will provide them with critical impact security fixes and selected urgent priority bug fixes.',
          display_name: 'Extended update support Term 2 ends',
          additional_text: '',
        },
        {
          name: 'Extended life phase',
          ptype: 'extended',
          tooltip:
            'The Extended Life Cycle Phase (ELP) is the post-retirement time period. We require that customers running Red Hat Enterprise Linux products beyond their retirement continue to have active subscriptions which ensures that they continue receiving access to all previously released content, documentation, and knowledge base articles as well as receive limited technical support. As there are no bug fixes, security fixes, hardware enablement, or root cause analysis available during the Extended Life Phase, customers may choose to purchase the Extended Life Cycle Support Add-On during the Extended Life Phase, which will provide them with critical impact security fixes and selected urgent priority bug fixes.',
          display_name: 'Extended life phase ends',
          additional_text: '',
        },
      ],
      versions: [
        {
          name: '5.0',
          type: 'Full Support',
          last_minor_release: null,
          final_minor_release: null,
          extra_header_value: null,
          additional_text: '',
          phases: [
            {
              name: 'General availability',
              date: '2026-09-01T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Extended update support',
              date: '2028-03-01T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
          ],
          tier: 'N/A',
          openshift_compatibility: null,
          extra_dependences: [],
        },
        {
          name: '4.16',
          type: 'Full Support',
          last_minor_release: null,
          final_minor_release: null,
          extra_header_value: null,
          additional_text: '',
          phases: [
            {
              name: 'General availability',
              date: '2024-06-27T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Full support',
              date: '4.17 GA + 3 months',
              date_format: 'string',
              additional_text: '',
            },
            {
              name: 'Maintenance support',
              date: '2025-12-27T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Extended update support',
              date: '2026-06-27T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Extended update support Term 2',
              date: '2027-06-27T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Extended life phase',
              date: 'N/A',
              date_format: 'string',
            },
          ],
          tier: 'N/A',
          openshift_compatibility: null,
          extra_dependences: [],
        },
        {
          name: '4.15',
          type: 'Full Support',
          last_minor_release: null,
          final_minor_release: null,
          extra_header_value: null,
          additional_text: '',
          phases: [
            {
              name: 'General availability',
              date: '2024-02-27T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Full support',
              date: '2024-09-27T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Maintenance support',
              date: '2025-08-27T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Extended update support',
              date: 'N/A',
              date_format: 'string',
            },
            {
              name: 'Extended update support Term 2',
              date: 'N/A',
              date_format: 'string',
              additional_text: '',
            },
            {
              name: 'Extended life phase',
              date: 'N/A',
              date_format: 'string',
            },
          ],
          tier: 'N/A',
          openshift_compatibility: null,
          extra_dependences: [],
        },
        {
          name: '4.14',
          type: 'Maintenance Support',
          last_minor_release: null,
          final_minor_release: null,
          extra_header_value: null,
          additional_text: '',
          phases: [
            {
              name: 'General availability',
              date: '2023-10-31T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Full support',
              date: '2024-05-27T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Maintenance support',
              date: '2025-05-01T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Extended update support',
              date: '2025-10-31T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Extended update support Term 2',
              date: '2026-10-31T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Extended life phase',
              date: '',
              date_format: 'string',
              additional_text: '',
            },
          ],
          tier: 'N/A',
          openshift_compatibility: null,
          extra_dependences: [],
        },
        {
          name: '4.13',
          type: 'Maintenance Support',
          last_minor_release: null,
          final_minor_release: null,
          extra_header_value: null,
          additional_text: '',
          phases: [
            {
              name: 'General availability',
              date: '2023-05-17T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Full support',
              date: '2024-01-31T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Maintenance support',
              date: '2024-11-17T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Extended update support',
              date: 'N/A',
              date_format: 'string',
            },
            {
              name: 'Extended update support Term 2',
              date: 'N/A',
              date_format: 'string',
              additional_text: '',
            },
            {
              name: 'Extended life phase',
              date: 'N/A',
              date_format: 'string',
            },
          ],
          tier: 'N/A',
          openshift_compatibility: null,
          extra_dependences: [],
        },
        {
          name: '4.12',
          type: 'Extended Support',
          last_minor_release: null,
          final_minor_release: null,
          extra_header_value: null,
          additional_text: '',
          phases: [
            {
              name: 'General availability',
              date: '2023-01-17T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Full support',
              date: '2023-08-17T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Maintenance support',
              date: '2024-07-17T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
            },
            {
              name: 'Extended update support',
              date: '2025-01-17T00:00:00.000Z',
              date_format: 'date',
              additional_text: '',
              superscript: '13',
            },
            {
              name: 'Extended update support Term 2',
              date: 'N/A',
              date_format: 'string',
              additional_text: '',
            },
            {
              name: 'Extended life phase',
              date: '',
              date_format: 'string',
              additional_text: '',
            },
          ],
          tier: 'N/A',
          openshift_compatibility: null,
          extra_dependences: [],
        },
      ],
      footnote: '',
      is_operator: false,
      show_openshift_compatibility: false,
      release_cadence: '4 months ',
      package: null,
      link: 'https://access.redhat.com/support/policy/updates/openshift/',
      policies: 'https://access.redhat.com/site/support/policy/updates/openshift/policies/',
    },
  ],
};

export { versionsData, lifecycleResponseData };
